@startuml

skinparam shadowing false

title Power Management State Diagram

state "Full Power" as Fp : entry: Set Display Brightness to Stored State\nentry: Set Bluetooth to Stored State\nentry: Set Health Notification to Stored State
state "Low Power" as Lp : entry: Trigger Motor Vibration for 2 secs\nentry: Set Display Brightness State = Low\nentry: Disable Bluetooth\nentry: Disable Health Notification 
state "Power Down" as Pd : entry: Turn Off Device

state Choice <<choice>>

[*] --> Choice
Choice --> Lp : [Battery SoC <= 10% &&\nBattery SoC > 2%]
Choice --> Fp : [Battery SoC > 10%]
Choice --> Pd : [Battery Soc <= 2%]

Fp -down-> Lp : [Battery SoC <= 10% ||\n Accelerometer Force < XN (5 secs)]
Lp -up-> Fp : [Battery SoC > 10% &&\nAccelerometer Force >= XN]
Lp -down-> Pd : [Battery SoC <= 2%]
Pd -> [*]


@enduml